name: Staging
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: itering/actions
          path: .github/actions
          persist-credentials: false
          ssh-key: "${{ secrets.ITERING_ACTIONS_DEPLOY_KEY }}"

      - name: Build And Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: quay.io/subscan-explorer/solc-compile-nodejs
          labels: ${{ steps.meta.outputs.labels }}

      - uses: 8398a7/action-slack@v3
        if: failure()
        with:
          status: ${{ job.status }}
          fields: repo,author,eventName,workflow,ref,commit
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
